version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

    ports:
      - "1433:1433"
    restart: always
    
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SqlPassword!

  webapp:
    build:
      context:  .
      dockerfile:  src\services\M2c\M2c.Api\Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
       - ConnectionStrings__CustomerDb=Server=db;Database=CustomerDb;User Id=sa;Password=SqlPassword!;
       - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: